package com.myteam;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestBillingDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String groupBillDate;
	private java.lang.String subscriptionDate;
	private double basePremium;

	private String frequency;

	private int frequencyValue;

	private int calenderDays;

	private java.lang.Boolean populateRoundValue;

	public RequestBillingDO() {
	}

	public java.lang.String getGroupBillDate() {
		return this.groupBillDate;
	}

	public void setGroupBillDate(java.lang.String groupBillDate) {
		this.groupBillDate = groupBillDate;
	}

	public java.lang.String getSubscriptionDate() {
		return this.subscriptionDate;
	}

	public void setSubscriptionDate(java.lang.String subscriptionDate) {
		this.subscriptionDate = subscriptionDate;
	}

	public double getBasePremium() {
		return this.basePremium;
	}

	public void setBasePremium(double basePremium) {
		this.basePremium = basePremium;
	}

	public java.lang.String getFrequency() {
		return this.frequency;
	}

	public void setFrequency(java.lang.String frequency) {
		this.frequency = frequency;
	}

	public int getFrequencyValue() {
		return this.frequencyValue;
	}

	public void setFrequencyValue(int frequencyValue) {
		this.frequencyValue = frequencyValue;
	}

	public int getCalenderDays() {
		return this.calenderDays;
	}

	public void setCalenderDays(int calenderDays) {
		this.calenderDays = calenderDays;
	}

	public java.lang.Boolean getPopulateRoundValue() {
		return this.populateRoundValue;
	}

	public void setPopulateRoundValue(java.lang.Boolean populateRoundValue) {
		this.populateRoundValue = populateRoundValue;
	}

	public RequestBillingDO(java.lang.String groupBillDate,
			java.lang.String subscriptionDate, double basePremium,
			java.lang.String frequency, int frequencyValue, int calenderDays,
			java.lang.Boolean populateRoundValue) {
		this.groupBillDate = groupBillDate;
		this.subscriptionDate = subscriptionDate;
		this.basePremium = basePremium;
		this.frequency = frequency;
		this.frequencyValue = frequencyValue;
		this.calenderDays = calenderDays;
		this.populateRoundValue = populateRoundValue;
	}

}