package com.myteam;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResponseBillingDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String ruleMessage;
	private double totalPremium;

	private String nextBillToDate;

	private int noOfBillingDays;

	private int noOfBillingMonths;

	private java.lang.Boolean populateRoundValue;

	public ResponseBillingDO() {
	}

	public java.lang.String getRuleMessage() {
		return this.ruleMessage;
	}

	public void setRuleMessage(java.lang.String ruleMessage) {
		this.ruleMessage = ruleMessage;
	}

	public double getTotalPremium() {
		return this.totalPremium;
	}

	public void setTotalPremium(double totalPremium) {
		this.totalPremium = totalPremium;
	}

	public java.lang.String getNextBillToDate() {
		return this.nextBillToDate;
	}

	public void setNextBillToDate(java.lang.String nextBillToDate) {
		this.nextBillToDate = nextBillToDate;
	}

	public int getNoOfBillingDays() {
		return this.noOfBillingDays;
	}

	public void setNoOfBillingDays(int noOfBillingDays) {
		this.noOfBillingDays = noOfBillingDays;
	}

	public int getNoOfBillingMonths() {
		return this.noOfBillingMonths;
	}

	public void setNoOfBillingMonths(int noOfBillingMonths) {
		this.noOfBillingMonths = noOfBillingMonths;
	}

	public java.lang.Boolean getPopulateRoundValue() {
		return this.populateRoundValue;
	}

	public void setPopulateRoundValue(java.lang.Boolean populateRoundValue) {
		this.populateRoundValue = populateRoundValue;
	}

	public ResponseBillingDO(java.lang.String ruleMessage, double totalPremium,
			java.lang.String nextBillToDate, int noOfBillingDays,
			int noOfBillingMonths, java.lang.Boolean populateRoundValue) {
		this.ruleMessage = ruleMessage;
		this.totalPremium = totalPremium;
		this.nextBillToDate = nextBillToDate;
		this.noOfBillingDays = noOfBillingDays;
		this.noOfBillingMonths = noOfBillingMonths;
		this.populateRoundValue = populateRoundValue;
	}

}